config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  root 'welcome#index'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  def index

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nerf War</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.erb
<style type="text/css">

	body {
		background: black;
	}

	#countdown { 
		height: 50px;
	}

	#wrapper {
    	position: fixed;
    	top: 50%;
    	left: 50%;
    	margin: -10% 0 0 -20%;
    	width: 40%;
    	height: 20%;
    	text-align: center;
    	color: #CCCCCC;
    	font-family: 'helvetica neue';

	}
	#wrapper a {
		color: #CCCCCC;
		text-decoration: none;
	}

	#wrapper p {
		font-family: 'helvetica neue';
		font-size: 16px;
	}

	#countdown {
		background: black;
		border: none;
		font-size: 30px;
		padding: 10px;
	}

	#logo {
		height: 100px;
		width: 100px;
		margin-top: 30px;
	}

</style>

<script type="text/javascript">
 //  $('[data-countdown]').each(function() {
 //   var $this = $(this), finalDate = $(this).data('countdown');
 //   $this.countdown(finalDate, function(event) {
 //     $this.html(event.strftime('%D days %H:%M:%S'));
 //   });
 // });

	// $('#clock').countdown('2020/10/10', function(event) {
	// 	$(this).html(event.strftime('%D days %H:%M:%S'));
	// });


$(document).ready(function(){
	var austDay = new Date(Date.UTC(2015, 8 - 1, 21, 19, 0));
	// austDay = new Date(austDay.getFullYear() + 2, 1 - 1, 26);
	$('#countdown').countdown({until: austDay});
});

// $(document).ready(function(){
//     $("div").click(function(){
//         $(this).hide();
//     });
// });
</script>
<!-- <p>If you click on me, I will disappear.</p>
<p>Click me away!</p>
<p>Click me too!</p> -->
<!-- <div id="defaultCountdown" data-countdown="2016/01/01"></div> -->
<div id="wrapper">
	<div id="content">
		<div id="countdown">
			<!-- <span id="clock"></span> -->
		</div>
		<div id="textContainer">
			<br />
			<p>The first rule of Nerf War is you DO NOT talk about Nerf War.</p>
			<br />
			<a href="http://engwiki.mtv/NerfWar">engwiki/NerfWar</a>
		</div>
		<div>
			<img id="logo" src="http://i.imgur.com/u0E4ice.png" />
		</div>
	</div>
</div>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>